window.appSettingsUiFromScript = {
  defaults: {
    defaultMask: 0,
    stepAnimationEnabled: true,
    stepAnimationDurationMs: 250,
    stepAnimationStartOpacity: 0.5,
    stepAnimationStartScale: 2.0,
    stepAnimationShowBorder: true,
    maskFadeDurationMs: 250,
    codeZoomStepPx: 4,
    codeZoomMinPx: 12,
    codeZoomMaxPx: 200,
    codeZoomHoldCount: 10,
    codeZoomBasePx: 22,
    codeZoomLineHeightMinPx: 16,
    codeZoomLineHeightRatio: 1.2,
    codeZoomLineHeightMaxOffsetPx: 8,
    transientStatusDelayMs: 500,
    presentationPointerRingEnabled: true,
    presentationPointerRingDurationMs: 400,
    presentationPointerRingSize: 120,
    presentationPointerRingColor: "rgba(60, 120, 255, 0.75)",
    presentationPointerRingShadowColor: "rgba(60, 120, 255, 0.25)",
    presentationPointerRingScaleStart: 1.4,
    presentationPointerRingScaleEnd: 0.35,
    presentationPointerRingEase: "ease-out",
    drawText: {
      forceUppercase: true,
      skipNonAlnum: false,
    },
    homeCursorDirection: "right",
    dataTemplates: [
      { value: "HelloWorld" },
      { value: "https://www.nkk.ac.jp/" },
      { value: "Cwm fjord-bank glyphs vext quiz." },
      { value: "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU" },
    ],
  },
};
