window.appSettingsFromScript = {
  defaults: {
    qrData: "HelloWorld",
    initialCode: 0,
    historyVisible: false,
    patternPanelOpen: false,
    layoutLeftPaneRatio: 0.5,
    debugVisible: false,
    skipExistingCells: false,
    autoAvoidTiming: false,
    overwriteDataOnFunctional: true,
    // defaultPut: -1=next, 0=透明, 1=黒(既定), 2=白
    defaultPut: 2,
    switchCount: 2,
    stepSpeed: 30,
    skipMode: false,
    stepSkipDataOnly: true,
    presentationMode: false,
    viewFlags: {
      viewCursor: true,
      viewGuide: true,
      viewGrid: true,
      viewEmpty: true,
      viewColor: true,
      viewDebugValues: true,
    },
    useDirection: false,
    codeSamples: [],
  },
};
