// ui/editor-config.js
window.OfflineCodeEditorConfig = {
  control: [
    "if",
    "else",
    "repeat",
    "loop",
    "while",
    "until",
    "for",
    "end",
    "endif",
    "endrepeat",
    "endloop",
    "endwhile",
    "enduntil",
    "endfor",
    "stop",
    "pause",
  ],
  command: [
    "move",
    "moveleft",
    "moveright",
    "moveup",
    "movedown",
    "turn",
    "reset",
    "base",
    "mask",
    "data",
    "text",
    "qrcode",
    "put",
    "timing",
    "skip",
    "finder",
    "finders",
    "alignment",
    "alignments",
    "dark",
    "darkmodule",
    "darkmodules",
    "format",
    "formats",
    "timings",
    "next",
    "pause",
  ],
  predicateWord: ["block","wall","empty","used","timing","skip","last"],
  switchNames: ["red","blue","green","yellow"],
  constants: ["left","right","up","down","on","off","flip"]
};
