// ui/editor-config.js
window.OfflineCodeEditorConfig = {
  control: [
    "if",
    "else",
    "repeat",
    "loop",
    "while",
    "until",
    "for",
    "end",
    "endif",
    "endrepeat",
    "endloop",
    "endwhile",
    "enduntil",
    "endfor",
  ],
  command: [
    "move",
    "turn",
    "reset",
    "base",
    "mask",
    "data",
    "qrcode",
    "put",
    "timing",
    "skip",
    "finder",
    "finders",
    "alignment",
    "alignments",
    "dark",
    "darkmodules",
    "format",
    "formats",
    "timings",
    "next",
    "pause",
    "hello",
    "helloworld",
    "drawhelloworld",
    "setswitch",
    "drawdataPatterns",
    "buildQRCode",
    "drawBasePatterns",
    "drawBasePatternsStepped",
    "drawFinderPatterns",
    "drawAlignmentPatterns",
    "drawDarkModulePatterns",
    "drawFormatPatterns",
    "drawTimingPatterns",
    "putFinderCells",
    "putAlignmentCells",
    "putDarkModuleCells",
    "putFormatCells",
    "putTimingCells",
  ],
  predicateWord: ["block","wall","empty","used","timing","skip","last"],
  switchNames: ["red","blue","green","yellow"],
  constants: ["left","right","up","down","on","off","flip","toggle","true","false"]
};
